# Generated by Django 5.1 on 2024-10-22 03:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='epica',
            name='estado_valido_epica',
        ),
        migrations.RemoveConstraint(
            model_name='tarea',
            name='estado_valido_tarea',
        ),
        migrations.AddConstraint(
            model_name='epica',
            constraint=models.CheckConstraint(condition=models.Q(('estado', 'POR_HACER'), ('estado', 'EN_PROGRESO'), ('estado', 'COMPLETADA'), _connector='OR'), name='estado_valido_epica'),
        ),
        migrations.AddConstraint(
            model_name='tarea',
            constraint=models.CheckConstraint(condition=models.Q(('estado', 'POR_HACER'), ('estado', 'EN_PROGRESO'), ('estado', 'COMPLETADA'), _connector='OR'), name='estado_valido_tarea'),
        ),
    ]
