# Generated by Django 5.1 on 2024-10-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0002_remove_epica_estado_valido_epica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='backlog_sprint',
            field=models.ManyToManyField(blank=True, related_name='sprint_backlog', to='scrum.tarea'),
        ),
    ]
