# Generated by Django 5.1 on 2024-10-22 03:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0003_alter_sprint_backlog_sprint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tarea',
            constraint=models.CheckConstraint(condition=models.Q(('prioridad', 'BAJA'), ('prioridad', 'MEDIA'), ('prioridad', 'ALTA'), _connector='OR'), name='prioridad_valido_tarea'),
        ),
    ]
