# Generated by Django 5.1.2 on 2024-10-24 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0004_tarea_prioridad_valido_tarea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_de_finalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='epica',
            name='nombre',
            field=models.CharField(help_text='Nombre descriptivo de la Epica.', max_length=200, verbose_name='Nombre de la Epica'),
        ),
        migrations.AlterField(
            model_name='epica',
            name='tareas_asociadas',
            field=models.ManyToManyField(blank=True, related_name='epicas_tareas', to='scrum.tarea'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='nombre',
            field=models.CharField(help_text='Nombre descriptivo del Sprint', max_length=100, verbose_name='Nombre del Sprint'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='titulo',
            field=models.CharField(help_text='Un titulo que describa la tarea.', max_length=200, verbose_name='Titulo de la Tarea'),
        ),
        migrations.AddConstraint(
            model_name='tarea',
            constraint=models.CheckConstraint(condition=models.Q(('estado', 'COMPLETADA'), ('fecha_de_finalizacion__isnull', True), _connector='OR'), name='fecha_finalizacion_tarea'),
        ),
    ]
